<?xml version="1.0" encoding="utf-8"?><Database Name="EET321_Lab4_S16" Class="EET321_Lab4DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=iet2;Initial Catalog=EET321_Lab4_S16;User ID=EET321" SettingsObjectName="_4_wire.Properties.Settings" SettingsPropertyName="EET321_Lab4_S16ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EET321_Lab4Table" Member="EET321_Lab4Tables">
    <Type Name="EET321_Lab4Table">
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Resistance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>